server:
  port: 3000
  servlet:
    encoding:
      charset: UTF-8
spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false


